arrowParens: "avoid"
bracketSpacing: true
endOfLine: "auto"
printWidth: 120
singleQuote: false
tabWidth: 2
trailingComma: "all"

overrides:
  - files: ["*.sol", "*.toml"]
    options:
      tabWidth: 4
